# Generated by Django 4.2.6 on 2023-10-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_admin_alter_attendance_id_alter_bursar_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('position', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=70)),
                ('username', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
