# Generated by Django 4.2.6 on 2023-11-18 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_admin_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingStudentApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_first_name', models.CharField(max_length=40)),
                ('student_last_name', models.CharField(max_length=40)),
                ('student_dob', models.DateField()),
                ('student_age', models.IntegerField()),
                ('student_gender', models.CharField(max_length=10)),
                ('student_former_primary', models.CharField(max_length=50)),
                ('student_index_no', models.CharField(max_length=40)),
                ('student_KCSE_marks', models.IntegerField()),
                ('parent_first_name', models.CharField(max_length=40)),
                ('parent_last_name', models.CharField(max_length=40)),
                ('parent_id_number', models.CharField(max_length=40)),
                ('parent_phone_number', models.CharField(max_length=40)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_address', models.CharField(max_length=40)),
                ('parent_username', models.CharField(max_length=40)),
                ('parent_password', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PendingTeachers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('id_number', models.TextField(max_length=20)),
                ('tsc_number', models.TextField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Bursar',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='FeedbackParentGuardian',
        ),
        migrations.DeleteModel(
            name='FeedbackTeacher',
        ),
        migrations.DeleteModel(
            name='Fees',
        ),
        migrations.DeleteModel(
            name='ParentGuardianNotification',
        ),
        migrations.DeleteModel(
            name='Results',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='TeacherNotification',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='date_of_birth',
            new_name='dob',
        ),
        migrations.RemoveField(
            model_name='parentguardian',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='parentguardian',
            name='child_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.AddField(
            model_name='parentguardian',
            name='id_number',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='parentguardian',
            name='username',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='id_number',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='tsc_number',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='admin',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='admin',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='admin',
            name='position',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='parentguardian',
            name='address',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='parentguardian',
            name='first_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='parentguardian',
            name='last_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='parentguardian',
            name='password',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='parentguardian',
            name='phone_number',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=250),
        ),
    ]
