# Generated by Django 4.2.6 on 2023-11-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pendingstudentapplication_pendingteachers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='staff_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
