# Generated by Django 4.2.6 on 2023-11-29 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_parentguardian_user_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='password',
        ),
        migrations.RemoveField(
            model_name='pendingstudentapplication',
            name='parent_password',
        ),
        migrations.RemoveField(
            model_name='pendingteachers',
            name='password',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='password',
        ),
    ]
