# Generated by Django 4.2.6 on 2023-12-11 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_remove_admin_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='age',
            new_name='student_age',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='student_class',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='dob',
            new_name='student_dob',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='student_first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='gender',
            new_name='student_gender',
        ),
        migrations.AddField(
            model_name='student',
            name='parent_address',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_first_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_id_number',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_last_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_phone_number',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='pendingstudentapplication',
            name='parent_address',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.DeleteModel(
            name='ParentGuardian',
        ),
    ]
