# Generated by Django 4.2.6 on 2023-12-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_student_student_index_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_index_no',
        ),
        migrations.AddField(
            model_name='student',
            name='former_school',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
