# Generated by Django 4.2.6 on 2023-12-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_student_student_index_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingstudentapplication',
            name='student_class',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
