# Generated by Django 4.2.6 on 2023-12-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_pendingstudentapplication_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_fee_balance',
            field=models.DecimalField(decimal_places=2, default=18000.0, max_digits=8),
        ),
    ]
